configuration-set.active=

configuration-set.web-app.profiles=web/headless/chrome
configuration-set.web-app.suites=web_app
configuration-set.web-app.environments=

configuration-set.rest-api.profiles=
configuration-set.rest-api.suites=rest_api
configuration-set.rest-api.environments=

configuration-set.ios-app.profiles=mobile_app/local2,mobile_app/ios
configuration-set.ios-app.suites=mobile_app/ios
configuration-set.ios-app.environments=

configuration-set.android-app.profiles=mobile_app/local2,mobile_app/android
configuration-set.android-app.suites=mobile_app/android
configuration-set.android-app.environments=

configuration-set.electron.profiles=desktop/electron,web/desktop/chrome
configuration-set.electron.suites=electron
configuration-set.electron.environments=
