configuration-set.web-sauce.profiles=web/headless/chrome/1920x1080
configuration-set.web-sauce.suites=web_app
configuration-set.web-sauce.environments=sauce

configuration-set.rest-api.profiles=
configuration-set.rest-api.suites=rest_api
configuration-set.rest-api.environments=api
