batch-1.resource-location=story/web_app
batch-1.resource-include-patterns=*.story
batch-1.threads=1

web.driver.chrome.command-line-arguments=--ignore-certificate-errors
engine.composite-paths=steps/web_app/*.steps
