batch-1.resource-location=story/rest_api
batch-1.resource-include-patterns=**/00-*.story
batch-1.threads=1

batch-2.resource-location=story/rest_api
batch-2.resource-include-patterns=**/*.story
batch-2.resource-exclude-patterns=**/00-*.story
batch-2.threads=1

http.ssl.check-certificate=false
