name: Mobile Demo Test Run

env:
  DEVICE_NAME: vividus-test-device
  IOS_DEVICE_TYPE_ID: iPhone 14 Pro Max

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * MON-FRI'
  push:
    branches:
    - main
    paths:
    - '**/mobile_app/**'
    - '**/android/**'
    - '**/ios/**'
    - '.github/workflows/mobile-test-run.yml'
  pull_request:
    branches:
    - main
    paths:
    - '**/mobile_app/**'
    - '**/android/**'
    - '**/ios/**'
    - '.github/workflows/mobile-test-run.yml'

permissions:
  contents: read

jobs:
  mobile-test-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - platform: Android
          os: ubuntu-latest
        - platform: iOS
          os: macos-latest
      fail-fast: false

    steps:
    - name: Checkout (including submodules)
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Enable KVM
      if: matrix.platform == 'Android'
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Cache tests history
      uses: actions/cache@v5
      with:
        save-always: true
        path: output/history
        key: tests-history-cache
        restore-keys: |
          tests-history-cache

    - name: Spin-up iOS simulator
      if: matrix.platform == 'iOS'
      run: xcrun simctl create "$DEVICE_NAME" "$IOS_DEVICE_TYPE_ID" | xargs xcrun simctl boot

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'gradle'

    - name: Install node
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'

    - name: Install Appium
      run: npm i -g appium@3.2.0

    - name: Install XCUITest driver
      if: matrix.platform == 'iOS'
      run: appium driver install xcuitest

    - name: Install UiAutomator2 driver
      if: matrix.platform == 'Android'
      run: appium driver install uiautomator2

    - name: Start appium server
      run: appium --relaxed-security --log-timestamp --log appium.log &

    - name: Run iOS tests
      if: matrix.platform == 'iOS'
      run: |
        ./gradlew runStories -Pvividus.configuration-set.active=ios-app \
                             -Pvividus.allure.history-directory=output/history/ios \
                             -Pvividus.selenium.grid.capabilities.showXcodeLog=true \
                             -Pvividus.selenium.grid.capabilities.wdaLaunchTimeout=360000 \
                             -Pvividus.selenium.grid.capabilities.appium\:simulatorStartupTimeout=600000 \
                             -Pvividus.selenium.grid.capabilities.udid="$(xcrun simctl list | grep "$DEVICE_NAME" | sed 's/[^(]*(\([^()]*\)).*/\1/g')" \
                             -Pvividus.selenium.grid.capabilities.deviceName="$DEVICE_NAME" \
                             -Pvividus.selenium.grid.http.read-timeout=PT15M


    - name: Run Android tests
      if: matrix.platform == 'Android'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        arch: x86_64
        target: google_apis
        avd-name: ${{ env.DEVICE_NAME }}
        emulator-boot-timeout: 240
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
        disable-animations: true
        script: >-
          ./gradlew runStories
          -Pvividus.configuration-set.active=android-app
          -Pvividus.allure.history-directory=output/history/android
          -Pvividus.selenium.grid.capabilities.deviceName="$DEVICE_NAME"

    - name: Publish ${{ matrix.platform }} tests report
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.platform }} tests report
        path: output/reports/allure

    - name: Print appium logs
      if: always()
      run: cat ./appium.log
