name: Demo Test Run

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 4 * * MON-FRI'

jobs:
  test-run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout (including submodules)
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Cache tests history
      uses: pat-s/always-upload-cache@v3.0.11
      with:
        path: output/history
        key: tests-history-cache
        restore-keys: |
          tests-history-cache

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'

    - name: Run REST API tests
      run: |
        ./gradlew runStories -Pvividus.configuration.suites=rest_api \
                             -Pvividus.allure.history-directory=output/history/rest-api-tests

    - name: Publish REST API tests report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: REST API tests report
        path: output/reports/allure

    - name: Run web application tests
      run: |
        ./gradlew runStories -Pvividus.configuration.suites=web_app \
                             -Pvividus.configuration.profiles=web/headless/chrome \
                             -Pvividus.allure.history-directory=output/history/web-app-tests

    - name: Publish web application tests report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Web application tests report
        path: output/reports/allure
